### ISSUE TITLE
Groups chat not disable.

### ISSUE THREAD

**Issue by IMDGhanshyam** [CometChat/ios-swift-chat-sdk-demo#4]
I want to disable groups chat in my iOS app

I had disabled the groups chat in the admin panel(https://51850.cometondemand.net/admin/?module=settings&action=generalsettings) but it does not work in the iOS.

![screenshot 2018-11-05 at 12 51 02 pm](https://user-images.githubusercontent.com/44672948/47983601-e946a600-e0f9-11e8-85ed-481a0be6377f.png)

**Comment by jeetkapadia** [comment]
Hi,

Due to aggressive caching for better performance, sometimes it may take upto an hour for the changes to reflect. Please check now and the Groups tab would be disabled by now. If you are still facing issues, please feel free to schedule a session with us:

https://www.cometchat.com/schedule-session
